#!/bin/bash

# Quick Debug Commands for Kiosk Hardware Issue
# Run these after connecting via wireless debugging

echo "=== Step 1: Connect to Kiosk ==="
echo "Run: adb connect <IP>:<PORT>"
echo ""
echo "=== Step 2: Verify Connection ==="
echo "Run: adb devices"
echo ""
echo "=== Step 3: Get Real-Time Logs ==="
echo "Run: adb logcat | grep -E 'PassportScanner|IDCard|InitIDCard|CheckDevice|Device online|Current device|Error|Failed'"
echo ""
echo "=== Step 4: Save Logs to Files ==="
echo "Run these commands:"
echo ""
echo "# SDK Initialization Logs"
echo "adb logcat -d | grep -E 'PassportScanner|InitIDCard' > init_logs.txt"
echo ""
echo "# Device Detection Logs"
echo "adb logcat -d | grep -E 'Device|CheckDevice|USB' > device_logs.txt"
echo ""
echo "# All Relevant Logs"
echo "adb logcat -d | grep -E 'PassportScanner|IDCard|USB|InitIDCard|CheckDevice|Device online|Current device' > all_logs.txt"
echo ""
echo "=== Step 5: Check USB Devices ==="
echo "adb shell lsusb"
echo ""
echo "=== Step 6: Check Device Info ==="
echo "adb shell getprop ro.product.model"
echo "adb shell getprop ro.build.version.release"
echo ""
echo "=== Share These Files ==="
echo "1. init_logs.txt"
echo "2. device_logs.txt"
echo "3. all_logs.txt"
echo "4. Output of: adb shell lsusb"
